### ISSUE TITLE
Hand over `mvs_input_directory` to functions that are called within a function

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#102]
If `mvs_input_directory` is a input parameter to a function it should be handed over to functions that are called within this functions, otherwise the information gets lost. 
See [here](https://github.com/greco-project/pvcompare/blob/208fef66afc8d8972999ea4cd03de7082ca6f635/pvcompare/demand.py#L226) for electricity demand, same for heat demand - I didn't check for other locations.

**Comment by SabineHaas** [comment]
I checked for `calculate_power_demand()`, it's been solved there.
Is this issue fully solved?

**Comment by Piranias** [comment]
i didn't check if this bug occurs anywhere else.. i think that was your idea right?

**Comment by SabineHaas** [comment]
Yes!
