### ISSUE TITLE
Found a website with a tool named PVCompare 

### ISSUE THREAD

**Issue by mahendrark** [greco-project/pvcompare#105]
Hi @SabineHaas and @Piranias 

I happened to stumble on this [website](http://www.pvcompare.net/) which hosts a seemingly commercial tool, also called PVCompare, to compare PV products. 

Not sure how it affects any aspect of GRECO's PVCompare, but just wanted to bring it to your attention.

**Comment by SabineHaas** [comment]
Thank you so much for sharing @mahendrark ! We will look into it and discuss - it's not too late to rename the tool.
@Piranias anyways I thought we might find a more "open" name, as one could use the tool for more than comparing PV technologies.

**Comment by SabineHaas** [comment]
There's no entry in data bases for market names - we keep the name for now, but are willing to rename the tool in case it is necessary.
