### ISSUE TITLE
Check unit of maximumCap of PV

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#109]
The unit of maximumCap of PV should be the same as the unit of the time series, I assume.
Could you please check the unit and add it [here](https://github.com/greco-project/pvcompare/blob/7ace8d6a2697d853ae00ae3ad4eba0dd4956a703/pvcompare/pv_feedin.py#L239-L243) to the comment?

**Comment by Piranias** [comment]
yes, it is calculated in kWh as well, it is also commented [here](https://github.com/greco-project/pvcompare/blob/7ace8d6a2697d853ae00ae3ad4eba0dd4956a703/pvcompare/pv_feedin.py#L603)
