### ISSUE TITLE
"label" in energyProduction causes error

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#12]
I adapted [this line](https://github.com/greco-project/pvcompare/blob/9931f6cf594d201992ac9e960015af7a4b803f25/pvcompare/adapt_csvs.py#L222) in adapt_csv.py and suddenly an error is raised. I do not get the connection between the investment flow and the label of the asset. @SabineHaas do you have a clue what this is about?
If I manually change it back to the way you defined it [here](https://github.com/greco-project/pvcompare/blob/update/csvs/pvcompare/data/mvs_inputs/csv_elements/energyProduction.csv#L7): "PV_si", "PV_cpv_180" and "PV_cpv_90" it works normal. 

Here's the error message:
```
 File "/home/adminlocal/Dokumente/greco_env/lib/python3.6/site-packages/pyomo/core/expr/numvalue.py", line 230, in value
    % (obj.name,))
ValueError: No value for uninitialized NumericValue object InvestmentFlow.invest[Solar inverter (mono),Electricity bus]
ERROR: evaluating object as numeric value: InvestmentFlow.invest[Solar
    inverter (mono),Electricity bus]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object InvestmentFlow.invest[Solar
    inverter (mono),Electricity bus]
14:04:54-ERROR-evaluating object as numeric value: InvestmentFlow.invest[Solar inverter (mono),Electricity bus]
    (object: <class 'pyomo.core.base.var._GeneralVarData'>)
No value for uninitialized NumericValue object InvestmentFlow.invest[Solar inverter (mono),Electricity bus]
```

**Comment by Piranias** [comment]
if I change the label to: PV_si_180_30 etc. I get the following error:

`ValueError: No value for uninitialized NumericValue object InvestmentFlow.invest[PV_cpv_90_90,PV plant (mono) bus]`

**Comment by SabineHaas** [comment]
I can reproduce the error with MVS dev. With MVS branch `feature/save_network_graph` I don't get the error. Could it be connected to the new constraint? That's what mainly has changed since then I think.

**Comment by SabineHaas** [comment]
> If I manually change it back to the way you defined it [here](https://github.com/greco-project/pvcompare/blob/update/csvs/pvcompare/data/mvs_inputs/csv_elements/energyProduction.csv#L7): "PV_si", "PV_cpv_180" and "PV_cpv_90" it works normal.

What do you mean by manually changing ist? Do you then execute the csvs with MVS directly or do you uncomment the lines in pvcompare that change the labels?

**Comment by SabineHaas** [comment]
I get the same error if I manually change the labels and uncomment the [lines](https://github.com/greco-project/pvcompare/blob/9931f6cf594d201992ac9e960015af7a4b803f25/pvcompare/adapt_csvs.py#L220-L222)  that change the labels.

**Comment by SabineHaas** [comment]
Was this issue solved?

**Comment by Piranias** [comment]
So I tried alot of different settings in the csv's but couldn't  find out where exactly the error came from. (For sure it was not the labels.) Then I replaced all of the csv's and suddenly it was working. So I'd say this is decrepit for now without solving it.
