### ISSUE TITLE
'Check_inputs' in 'create_pv_components()' checks 'directory_energy_production' instead of 'mvs_input_directory'

### ISSUE THREAD

**Issue by MaGering** [greco-project/pvcompare#124]
@c-moeller and I found that running the main with mvs_input_directory specified to the mvs_inputs_template_sector_coupling directory we get a ValueError, because "the number of pv powerplants in energyProduction.csv differs from the number of powerplants listed in pv_setup.csv." This is due to a input check in function create_pv_components() in pv_feedin.py.

We were wondering if the check shouldn't look like this:
`    # check if mvs_input/energyProduction.csv contains all power plants
    check_inputs.check_mvs_energy_production_file(pv_setup, mvs_input_directory)`

instead of this:
`    # check if mvs_input/energyProduction.csv contains all power plants
    check_inputs.check_mvs_energy_production_file(pv_setup, directory_energy_production)`

**Comment by Piranias** [comment]
I don't understand the use case. The "directory_energy_production" should be in "mvs_input_directory", why wouldn't it be?

**Comment by MaGering** [comment]
That is exactly the question I guess. In which case is directory_energy_production used instead of mvs_input_directory?

The use case was the following: When @c-moeller and I ran the simulation from mvs_inputs_template_sector_coupling directory the check has been made for mvs_inputs instead and we got the error message. We were wondering if that is correct or if the check should compare mvs_inputs_template_sector_coupling and pv_setup.csv.

**Comment by Piranias** [comment]
It's because energyProduction.csv in  mvs_inputs_template_sector_coupling is different from the mvs_inputs right now. You need to check "pv_setup.csv" in "inputs" and adjust the powerplants you want to use. The number of powerplants should be the same in "pv_setup.csv" and "eergyProduction.csv".
hope this becomes clearer

**Comment by SabineHaas** [comment]
> That is exactly the question I guess. In which case is directory_energy_production used instead of mvs_input_directory?
> 
> The use case was the following: When @c-moeller and I ran the simulation from mvs_inputs_template_sector_coupling directory the check has been made for mvs_inputs instead and we got the error message. We were wondering if that is correct or if the check should compare mvs_inputs_template_sector_coupling and pv_setup.csv.

The check should be made for mvs_inputs_template_sector_coupling in your case as this is your input folder.

**Comment by Piranias** [comment]
sorry closed this on accident ;)
