### ISSUE TITLE
parameter values: energy_price in energyProviders

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#14]
Hi,
so I added the new opex_fix to 140 Euro/kpW/year to our PV plants.
Still when running the simulation no PV components are used with the current settings. My guess is that we need to adapt the energy_price in energyProviders.

Here's what I found out from the simulation: the PV plants (only SI) are starting to be used only if energy_price is 0.5 or higher. if energy_price =also the cpv cells on the flat roof are beeing used.

@mahendrark did you already research on the enery price? is it fixed at 0.3 or is there a variance on the price?

@mahendrark @SabineHaas , so you have other ideas which parameters we could adapt to make the system running?

**Comment by mahendrark** [comment]
@Piranias , for Germany, the average household price for electricity was hovering around 0.30 
€/kWh for the last three years, as per the data in [this](https://ec.europa.eu/eurostat/statistics-explained/images/d/d9/Electricity_prices%2C_first_semester_of_2017-2019_%28EUR_per_kWh%29.png)

So I guess we cant change that value.

**Comment by Piranias** [comment]
it shows that by lowering the opex_fix to 50 euros/kWp (see issue #13 ) the system uses all of the pv plants! yay
