### ISSUE TITLE
Define efficient output structure

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#147]
Right now there is several pvcompare outputs:
1) mvs_output folder with figures, reports and mvs_input folder
2) seperate loop output directory, where all the scalars.xlsx and timeseries_all_busses_xlsx are stored in
3) plotting functions (in ploty.py, see PR #144) scpecified for pvcompare-outputs

The mvs_output folder is overwritten each simulation. So the workflow right now is that one has to copy the mvs_output folder, and the loop_output_folder, give it a new name and specify the new directory within the plotting functions. 
I suggest a new workflow that keeps us from mixing up all the outputs:

* a new input parameter "scenario_name" is introduced in main() (alternatively/additionaly the scenario name could be loaded from or written into project_data.csv - "project_name")
* first of all it is checked whether the same scenario_name_folder already exists. If yes, one has to provide a different  scenario name.
* after applying mvs in main.py the mvs_output folder is copied automatically to pvcompare/data/scenario_outputs/"scenario_name"-folder
* loop outputs are also stored within this "scenario_folder", so we have all at one place (so a new folder is created within: pvcompare/data/scenario_outputs/"scenario_name"-folder/loop_outputs/...
* the plotting functions get the parameter "scenario_name" and adjust the paths for the timeseries accordingly

what do you think? Anything missing?

**Comment by SabineHaas** [comment]
> Right now there is several pvcompare outputs:
> 
>     1. mvs_output folder with figures, reports and mvs_input folder
> 
>     2. seperate loop output directory, where all the scalars.xlsx and timeseries_all_busses_xlsx are stored in
> 
>     3. plotting functions (in ploty.py, see PR #144) scpecified for pvcompare-outputs
> 
> 
> The mvs_output folder is overwritten each simulation. So the workflow right now is that one has to copy the mvs_output folder, and the loop_output_folder, give it a new name and specify the new directory within the plotting functions.
> I suggest a new workflow that keeps us from mixing up all the outputs:
> 
>     * a new input parameter "scenario_name" is introduced in main() (alternatively/additionaly the scenario name could be loaded from or written into project_data.csv - "project_name")

I would vote for reading it from `project_data.csv` (running scenarios again seems faster for me like that), but @Piranias and @MaGering should decide, as you use the tool mainly. In `project_data.csv` you can find `project_name`, `scenario_id` and `scenario_name`: maybe a combination of these would be useful for the name of the output folder.

> 
>     * first of all it is checked whether the same scenario_name_folder already exists. If yes, one has to provide a different  scenario name.
> 
>     * after applying mvs in main.py the mvs_output folder is copied automatically to pvcompare/data/scenario_outputs/"scenario_name"-folder
> 
>     * loop outputs are also stored within this "scenario_folder", so we have all at one place (so a new folder is created within: pvcompare/data/scenario_outputs/"scenario_name"-folder/loop_outputs/...
> 
>     * the plotting functions get the parameter "scenario_name" and adjust the paths for the timeseries accordingly

You could just adapt `output_directory` the plotting functions.

> 
> 
> what do you think? Anything missing?

:+1:

**Comment by Piranias** [comment]
> In project_data.csv you can find project_name, scenario_id and scenario_name: maybe a combination of these would be useful for the name of the output folder.

I agree, maybe "scenario_name_scenario_id" would be good. We could also have a feature that sets "scenario_id" +1 if the output folder already exists. 

> You could just adapt output_directory the plotting functions.

eventually yes, but the point is that each output directory will be different and therefore the output_directory needs to be adapted by "scenario_name". That's what I meant

**Comment by MaGering** [comment]
> I agree, maybe "scenario_name_scenario_id" would be good. We could also have a feature that sets "scenario_id" +1 if the output folder already exists.

This sounds like a really cool feature! :)

I like the new structure and also the solution to the loop output! Thanks a lot @Piranias!

**Comment by MaGering** [comment]
>     * first of all it is checked whether the same scenario_name_folder already exists. If yes, one has to provide a different  scenario name.

This means I will have to delete the results each time before I rerun the same scenario with different input parameters for example?

**Comment by Piranias** [comment]
> This means I will have to delete the results each time before I rerun the same scenario with different input parameters for example?
correct. or you give it a new name. Another option would be what I suggested above:

> ... maybe "scenario_name_scenario_id" would be good. **We could also have a feature that sets "scenario_id" +1 if the output folder already exists.**

so if the same scenario_name folder already exists it returns a warning and sets up scenario_id + 1 . So you would have folders like: "scenarioA_1", "scenarioA_2" etc. and no folder would be overwritten.

open Questions:
@MaGering, do you think only "scenario_name + scenario_id" would be enough? Or do we also need the "project_name"? (I couldn't think of a case where we would need it.)
@MaGering : would you prefer that you need to change scenario_name and -id in project_data.csv or to enter it into "main.py" as an input parameter?

**Comment by MaGering** [comment]
> > ****
> 
> so if the same scenario_name folder already exists it returns a warning and sets up scenario_id + 1 . So you would have folders like: "scenarioA_1", "scenarioA_2" etc. and no folder would be overwritten.
> 
Oh yeah, right! :)

> open Questions:
> @MaGering, do you think only "scenario_name + scenario_id" would be enough? Or do we also need the "project_name"? (I couldn't think of a case where we would need it.)
Maybe to distinguish sector-coupling from electricity only scenarios.

> @MaGering : would you prefer that you need to change scenario_name and -id in project_data.csv or to enter it into "main.py" as an input parameter?
No, I just forgot that you don't have to change the "project_name" with this feature. ;)  I would like the idea though of only creating a new folder if something has changed, so there aren't new output folders if I just rerun the main without changing anything. Is it difficult to implement this?

**Comment by Piranias** [comment]
after talking to @MaGering we agreed on: 

- scenario_name as input in main.py + adapt scenario name in project_data.csv. Different variations of of one scenario are defined in "scenario_name" (e.g. Scenario_A1, "Scenario_A2" etc.) (project name and scenario id is not used.)
- no overwrite functionality, no counting up of scenario_id. error if scenario_name already exists.
