### ISSUE TITLE
parameter values: capex_var in energyConversion

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#15]
The capex_var in energyConversion is set to 3000 Euro. In my csv and in the read the docs it says Euro/kW:
[read the docs](https://mvs-eland.readthedocs.io/en/latest/MVS_parameters.html)

in the [link](https://understandsolar.com/solar-inverter-costs/) @mahendrark posted to the googledoc they propose an average price of 0.18 $/W which makes about 170 Euro/kW. How did you calculate the 3000 Euros?

**Comment by mahendrark** [comment]
@Piranias 

I just rechecked my calculations. You are right. Its 170 €/kW. 
I mistakenly considered the installation costs of the total system and added that to the inverter per kW costs, or maybe I was looking at the prices of the inverters in market. Either way, that is a wrong value. Thanks for checking it!
