### ISSUE TITLE
Generalize `check_inputs.add_parameters_to_energy_production_file()`

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#152]
Generalize `check_inputs.add_parameters_to_energy_production_file()` so that the column names of `energyProduction.csv` are free to choose.

Note: With #151 the column name is changed to PV + technology.

**Comment by SabineHaas** [comment]
This is important in case you want to give your own labels by defining your own column names. When merging #151 the label will be `PV + technology` - if this is fine for you @Piranias and @MaGering  we can move this issue to "Late issue".

**Comment by Piranias** [comment]
I just saw this. So we need to have some kind of indicator which technology it is we are looking at. If this doesn't happen in "label" it should happen in "column_name". So we need to decide on a coherent naming of the columns. Or, @SabineHaas is it very important to you that the columns can be named randomly?

**Comment by Piranias** [comment]
I now took "PV + technology" as the scheme for naming the columns.

**Comment by SabineHaas** [comment]
In the example the column name is still `pv_plant_01` by the way, see [here](https://github.com/greco-project/pvcompare/blob/dev/examples/example_user_inputs/mvs_inputs_electricity_sector/csv_elements/energyProduction.csv)

I did not mean the outcome of the column name but the original column name. So, could a user name the columns differently or do they have to follow a scheme? If they have to follow a scheme this should be documented in a prominent place in the docs.

**Comment by Piranias** [comment]
> In the example the column name is still `pv_plant_01` by the way, see [here](https://github.com/greco-project/pvcompare/blob/dev/examples/example_user_inputs/mvs_inputs_electricity_sector/csv_elements/energyProduction.csv)
> 
> I did not mean the outcome of the column name but the original column name. So, could a user name the columns differently or do they have to follow a scheme? If they have to follow a scheme this should be documented in a prominent place in the docs.

already answered this above:
` So we need to have some kind of indicator which technology it is we are looking at. If this doesn't happen in "label" it should happen in "column_name". So we need to decide on a coherent naming of the columns. Or, @SabineHaas is it very important to you that the columns can be named randomly?`


That's why I now adapted the scheme to "PV + technology". I will change it in examples as well.

I didn't update the documentation with any of the recent changes, so this still needs to be done.
