### ISSUE TITLE
parameter values: capex var in energyProduction

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#16]
according to [this](https://www.solaranlage-ratgeber.de/photovoltaik/photovoltaik-wirtschaftlichkeit/photovoltaik-anschaffungskosten) reference, the costs of aquisition are calulated as follows:

for a system up to 10 kWp:

solar modules: 0,45 Euro - 0,90 Euro / Wp
**solar inverter: ca 230 Euro/kW**
cabels: 100 - 500 Euro
assembly robotics: 100 - 150 Euro/ kWp
installation: 200 Euro/ kWp
feedin-module:  at least 150 Euro

makes  1.450 Euro/kWp with the inverter. Without inverter: ca. **1220 Euro/kWp**. this is alot more than martha assumed (340 Euro/kWp)

**Comment by SabineHaas** [comment]
on hold for now
