### ISSUE TITLE
[documentation] Fill section selected scenarios and results

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#160]
- [ ] overview over scenarios
- [ ] main research questions
- [ ] results of selected scenarios

Probably we cannot show all results here but just a selection of scenarios and results that might be interesting for other users (and might serve as examples).

**Comment by Piranias** [comment]
I'm not quite sure if this should be in the github / read the docs at all. The scenarios we are calculating are just a few examples of what one can do, but there is alot more options. I don't see the point in defining all of them in detail on the rtd. I would leave it with the "example" only. also I don't think github is the right place to publish the greco results. It is good to show what you _can_ do with pvcompare, but this can be shown in the example, starting from a research question and endling with results and plots..

**Comment by SabineHaas** [comment]
As we are writing the working paper we will not have this section in the way it was described in this issue. However, we can add additional results, as already done, in [this section](https://pvcompare.readthedocs.io/en/latest/scenarios_and_results.html#greco-results).
