### ISSUE TITLE
[documentation] examples section - add binder launch

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#161]
We should give examples for pvcompare. At first I thought that the scenarios and results could serve as example section. However, this section might not include any code, which I would see as requirement for an example. 

What do you think @Piranias? 

For mixing code and test I would use a jupyter notebook that can be easily included (one line statement) into the docs. You can check the [windpowerlib examples](https://windpowerlib.readthedocs.io/en/stable/modelchain_example_notebook.html) to see how it looks like.

If we add an example section we also need to adapt the text in "Examples and basic usage" of `README` and `getting_started.rst`.

**Comment by Piranias** [comment]
> What do you think @Piranias?
 sounds good!

> For mixing code and test I would use a jupyter notebook that can be easily included (one line statement) into the docs. You can check the [windpowerlib examples](https://windpowerlib.readthedocs.io/en/stable/modelchain_example_notebook.html) to see how it looks like.

what do you mean with "test"?

> 
> If we add an example section we also need to adapt the text in "Examples and basic usage" of `README` and `getting_started.rst`.

**Comment by SabineHaas** [comment]
> what do you mean with "test"?

text ;)

**Comment by SabineHaas** [comment]
Let's use binder for the examples. Users do not even have to install pvcompare then, as all packages are installed with binder, check e.g. [feedinlib](https://github.com/oemof/feedinlib) (there's a badge in the readme that links to binder),  and [binder launch](https://mybinder.org/v2/gh/oemof/feedinlib/dev) of feedinlib.

**Comment by SabineHaas** [comment]
I think we already provide good examples. The binder would be nice to have but we would also have to create jupyter notebooks for binder. This would be nice and interactive, but I think the examples that can be run and adapted for simulations are more important.
