### ISSUE TITLE
Pvcompare main / run_pvcompare

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#164]
To ensure the easy usage of pvcompare I would like to have one file that is used by the user to run pvcompare.

My suggestion is to add a `run_pvcompare.py` to the `pvcompare` directory (dir where setup.py lies), which calls the main functions. We could think about including automated loops, but the main goal is to have a file that is very simple.

Exemplary folder structure:
```
- /pvcomare
	- /docs
	- /pvcompare
	- ... 
	- run_pvcompare.py
        - setup.py
	- ... 
```

`run_pvcompare.py` could look like the following:
```
import xyz
from pvcompare import main

main.main(
    latitude=52.5243700,
    longitude=13.4105300,
    year=2014,
    population=48000,
    country="Germany",
)
main.apply_mvs()
```

Let me know what you think @Piranias @MaGering :)

**Comment by Piranias** [comment]
I guess you mean one file run_pvcompare.py (and not another run_simulations.py)?
For me that's fine. I already thought about renaiming the main.py file and/or the main() function as well. We could e.g. change 
main() -> apply_pvcompare(), so it's more intuitive, what do you think?

**Comment by SabineHaas** [comment]
> I guess you mean one file run_pvcompare.py (and not another run_simulations.py)?

yes, thanks adapted it above to ease confusion

> For me that's fine. I already thought about renaiming the main.py file and/or the main() function as well. We could e.g. change
> main() -> apply_pvcompare(), so it's more intuitive, what do you think?

that sounds good!

**Comment by SabineHaas** [comment]
connected to #172
