### ISSUE TITLE
output: what does the storage flows show us?

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#17]
Hi, 
i noticed that the storage output is always less (about 80 %) of the storage input. Do you know why?

Also I was a little confused with this illustration. Do you know what levels the output flow to exactly  3780 kWh?

![Bildschirmfoto_2020-04-22_16-34-05](https://user-images.githubusercontent.com/44803304/79996409-bb554d00-84b8-11ea-85b0-c128dd52a9bd.png)

**Comment by Piranias** [comment]
also this plot shows whats happening really clear. even though the storage capacity is super high, only a small propotion in charged and even a smaller propotion is discharged.

![Bildschirmfoto_2020-04-22_16-48-14](https://user-images.githubusercontent.com/44803304/79997049-6b2aba80-84b9-11ea-9948-8cd8e0338c4f.png)

**Comment by SabineHaas** [comment]
Could you upload the timeseries and scalars please? It might help me to understand what is happening.

> i noticed that the storage output is always less (about 80 %) of the storage input. Do you know why?

Is the efficiency of the storage 80 %?

**Comment by Piranias** [comment]
yes sure, i meant to do that. I just pushed all the new parameters into the dev branch.

**Comment by Piranias** [comment]
sorry i just noticed theres some bugs still. I will update you as soon as i fixed them

**Comment by Piranias** [comment]
ok, so the dev should be up to date now. note that I had to change the energy_price to 0.4 instead of 0.3 in order to have the system install pv plants at all. I'm still trying to figure out why this is, but in order to interpret the storage plots it should be enough :)

**Comment by smartie2076** [comment]
Hi, @mahendrark asked me to comment. Will try do do this sometime today/tomorrow.

**Comment by smartie2076** [comment]
> Also I was a little confused with this illustration. Do you know what levels the output flow to exactly 3780 kWh?

I am taking a guess here, as I do not have all the outputs. As you are including [an charge controller with costs](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/mvs_inputs/csv_elements/energyConversion.csv) in the optimization, it could be that it simply does not pay off to discharge more than that transformer capacity (ie. increase charge controller capacity to over 3780 kW). 
Whats weird then is why compared to that the storage´s in/output power is still so high. Could be, however, because [it simply is cost-free to install a lot input/output power](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/mvs_inputs/csv_elements/storage_01.csv). Same goes for the capacity. 

I would say you need to change the costs of storage to something, otherwise the charge controller determines the output flow maximum,  and there is no limit to the storage´s capacitites.

**Comment by Piranias** [comment]
> > Also I was a little confused with this illustration. Do you know what levels the output flow to exactly 3780 kWh?
> 
> I am taking a guess here, as I do not have all the outputs. As you are including [an charge controller with costs](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/mvs_inputs/csv_elements/energyConversion.csv) in the optimization, it could be that it simply does not pay off to discharge more than that transformer capacity (ie. increase charge controller capacity to over 3780 kW).
> Whats weird then is why compared to that the storage´s in/output power is still so high. Could be, however, because [it simply is cost-free to install a lot input/output power](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/mvs_inputs/csv_elements/storage_01.csv). Same goes for the capacity.
> 
> I would say you need to change the costs of storage to something, otherwise the charge controller determines the output flow maximum, and there is no limit to the storage´s capacitites.

thanks @smartie2076 . With "change the costs of storage to something" I guess you mean the opex_var in column storage_capacity?
I noticed that you choose a value of 4000 here. But I found [here](https://www.energieheld.de/solaranlage/photovoltaik/stromspeicher/kosten#preis-pro-kilowattstunde-berechnen) that the price/kWh is arount 0.20 - 0.30 Euro including the investment costs. Maybe that' interesting for you too.

**Comment by smartie2076** [comment]
> thanks @smartie2076 . With "change the costs of storage to something" I guess you mean the opex_var in column storage_capacity?

No, I mean capex_var for the input/output power. But actually, this might also be already fixed if the capex_var of the sotrage capacity weren´t so low (see below).

> I noticed that you choose a value of 4000 here. But I found [here](https://www.energieheld.de/solaranlage/photovoltaik/stromspeicher/kosten#preis-pro-kilowattstunde-berechnen) that the price/kWh is arount 0.20 - 0.30 Euro including the investment costs. Maybe that' interesting for you too.

The price per kWh of 0.20 - 0.30 Euro that you are citing is referring to the opex_var, afaik, not the capex_var of the storage capacity. This is the calculation they use to get to that for the battery *Sonnen eco 8 /10*:

> 16.500 € / (10 kWh * 1 Entladetiefe * 10.000 Zyklen * 0,98 Systemwirkungsgrad) = 16,83 Cent pro Kilowattstunde

It might be interesting to figure out if these opex_var would be a better figure for the optimization than the specific investment costs capex_var (16.500 €/10 kWh), but I always used the capex_var, ie. something like 400€/kWh Li-Ion or 200 €/kWh Pb battery.

**Comment by SabineHaas** [comment]
Can we close this issue @Piranias ?
