### ISSUE TITLE
[pvcompare] loop over different weather years

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#171]
For our simulations we use only one weather year. in order to specify which one resembles an average year we should either:
a) just compare different weather years for different locations (germany, spain) 
b) calculate timeseries for different years
c) run the simulations of the different scenarios for different weather years

@SabineHaas ,what do you think?

**Comment by SabineHaas** [comment]
I would like to discuss that in our meeting next week (appointment follows). It's about weighing up detail against complexity.
