### ISSUE TITLE
[pvcompare] write function to loop over pvcompare parameters

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#172]
This function should allow to change one (or a few associated) parameters of pvcompare in a loop. Up to now I evaluated 4 different cases, that the user can choose from. I need to pre-define the cases because there is no general procedure of changing single variables in pvcompare. The four cases are:

1) Location : (lat, lon, country in apply_pvcompare() )
2) year
3) number_of_storeys: (population in apply_pvcompare() and `number of storeys`in building_parameters.csv)
4) Technology: (Technology in pv_setup, while setup configuration stays the same)

@MaGering @SabineHaas can you please comment if you can think of other cases that one/we might want to loop over? Thx

**Comment by MaGering** [comment]
For me it would be also interesting to loop over `temp_high` in [heat_pumps_and_chillers.csv](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/inputs/heat_pumps_and_chillers.csv), the high temperature of the heat pump.
