### ISSUE TITLE
[Bug] test_demand : with and without warm water

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#175]
In test_demand.py ->test_calculate_heat_demand(self):

the if statement for the assert doesn't make sense here. A test should always be static. If you want to test two options (with ww and without), you need to write another test where this value is changed before calculating the demand. Otherwise only the first case will be tested.

**Comment by MaGering** [comment]
Thank you for finding this! I fixed it in PR https://github.com/greco-project/pvcompare/pull/177
