### ISSUE TITLE
[Bug] XLRDError: Excel xlsx file; not supported

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#178]
This bug occurs in #174 and #177.

The excel reader has problems with the xlsx files. This occurs only on travis, works fine locally. Tried fixing it by including:
openpyxl>=3.0.5
xlrd>=1.0.0

to requirements and adapting the pandas version.

I don't understand why this happens now and not before (see update to mvs). The last merge was successfull even though the test_plots were already included here, see: https://github.com/greco-project/pvcompare/commits/dev

Error message: https://travis-ci.com/github/greco-project/pvcompare/jobs/459193436#L951

@SabineHaas , any idea?

Checklist to make sure that the bug report ist complete:
- [x] OS: Ubuntu 20.04.1 LTS
- [x] Branch: fix/test_demand, output_structure, 
- [x] If applicable: Attach full error message
- [ ] If applicable: Share screenshots/images of your problem
- [ ] If applicable: Share used input data

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Checkbox is not applicable to this bug report

**Comment by SabineHaas** [comment]
I have restarted the `dev` build and it also fails: see [here](https://travis-ci.com/github/greco-project/pvcompare/builds/207457939). So it's something that has changed in the package or the CI.

**Comment by Piranias** [comment]
so appearently xlrd has explicitly removed support for anything other than xls files.
 https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported

On python 3.7 this runs through, but not on python 3.6. That's why the tests are failing on travis.

**Comment by exeptionerror** [comment]
See Also [[Solved] xlrd.biffh.XLRDError: Excel xlsx file; not supported](https://exerror.com/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported/)

**Comment by bernyosuna** [comment]
IndexError: list index out of range

**Comment by giordanososa** [comment]
> so appearently xlrd has explicitly removed support for anything other than xls files.
> https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported
> 
> So we need to add the engine openpyxl.
> df = pd.read_excel("myFile.xlsx", sheet_name=2, engine='openpyxl')
> 
> But this only works for python 3.7 but not on python 3.6. That's why the tests are failing on travis.

also works on 3.8

**Comment by puransinha** [comment]
Perfect!! yes its a great help to resolve this issue using Engine. 

df = pd.read_excel("myFile.xlsx", sheet_name=2, engine='openpyxl')

Thanks a Lot

**Comment by exeptionerror** [comment]
Here Is All Possible Solution Added Please Look At Here[ [Solved] xlrd.biffh.XLRDError: Excel xlsx file; not supported in python](https://exerror.com/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported/)

**Comment by iamamanprajapati** [comment]
@puransinha
Thanks, I am using only

excelData = pd.read_excel('students.xlsx', engine='openpyxl')

it worked perfectly

**Comment by saiiitkgp713** [comment]
@puransinha @iamamanprajapati 

i tried the very same code you people suggested, but it is showing me BadZipFile error

a = pd.read_excel('multi-directory-excel/1985/1985.xlsx', engine='openpyxl')

![image](https://user-images.githubusercontent.com/10405832/115993580-19979d00-a5f1-11eb-87ba-d0e61644c918.png)
