### ISSUE TITLE
[Bug] test mvs for benchmark test

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#181]
Hi,
When trying to run tests for mvs I get the following error:

![mvs_fails](https://user-images.githubusercontent.com/44803304/102110708-c721c500-3e35-11eb-9601-ad56ba6c4d9a.png)

any idea what this is about?

Checklist to make sure that the bug report ist complete:
- [x] OS: Ubuntu 20.04.1 LTS
- [x] Branch: benchmark tests
- [x] If applicable: Attach full error message
- [x] If applicable: Share screenshots/images of your problem
- [ ] If applicable: Share used input data

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Checkbox is not applicable to this bug report

**Comment by SabineHaas** [comment]
there's an argument that is not recognized.. I've never seen this argument `test_mvs`
I didn't understand which tests you are running. Tests you have newly added to pvcompare? At which branch?
