### ISSUE TITLE
read in specific energy_price for country

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#19]
looking at [this](https://ec.europa.eu/eurostat/statistics-explained/images/d/d9/Electricity_prices%2C_first_semester_of_2017-2019_%28EUR_per_kWh%29.png) reference, i noticed that the energy price differs a lot between country (from 0.08 -0.3 Euro/kWh). I think we should probably write a function that reads in the specific energy price for that country.  

@SabineHaas do you agree?

**Comment by SabineHaas** [comment]
This sounds like a nice help for our users! I expected the user to provide the price but if it's easy to write this function / get the data for you - I think it's a nice feature!
