### ISSUE TITLE
are the investment costs allocated over the lifetime of the asset?

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#20]
Hi, 
the header already tells what this is about. I was wondering how the investmentcosts (especially opex_var in energyProduction) are allocated of the lifetime of the modules or the lifetime of the project?
Do you, @SabineHaas know how this is done in MVS?

**Comment by SabineHaas** [comment]
I do not know the economical functions of MVS in detail - but here's what might help you: 

[`evaluate_lifetime_costs()`](https://github.com/rl-institut/mvs_eland/blob/d7341742f0eed0f7235533aec3670c5604fd4121/src/C0_data_processing.py#L848) shows how the "annuity_capex_opex_var" that is used in D1 for the Investment objects of components to be optimized (see f.e. [`source_non_dispatchable_optimize()`](https://github.com/rl-institut/mvs_eland/blob/d7341742f0eed0f7235533aec3670c5604fd4121/src/D1_model_components.py#L410-L411)  is calculated.

Check also[ `capex_from_investment()`](https://github.com/rl-institut/mvs_eland/blob/d7341742f0eed0f7235533aec3670c5604fd4121/src/C2_economic_functions.py#L31) for detailed information on how lifetime and project_life is considered. Attention: There's an [open issue](https://github.com/rl-institut/mvs_eland/issues/247) about this function right now. 

 `opex_var` are operational costs (not investment) and are provided as 'variable_costs' to the oemof compontents  (see [D1](https://github.com/rl-institut/mvs_eland/blob/dev/src/D1_model_components.py))

**Comment by Piranias** [comment]
ok, thanks @SabineHaas , especially for mentioning the issue. 

For sure there must be something wrong here. If I set project_duration to one year, only PV plants are installed, if i change it to 15 years no pv plants are installed. This might also be interesting for smartie, unfortunately I cannot link her to this issue..

**Comment by SabineHaas** [comment]
I link the [MVS issue here.](https://github.com/rl-institut/mvs_eland/issues/289#issuecomment-621305110)
