### ISSUE TITLE
Research about gas prices of EU countries

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#208]
We are looking for gas prices for EU countries for households in 2020 (if not available for 2019). 
The outcome should be a table like the table for [electricity prices](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/static_inputs/electricity_prices.csv), although only one year (2020 or 2019) is enough. 

I've made a quick first research and found the following sources:
- https://www.statista.com/statistics/1047173/natural-gas-prices-for-households-european-union-country/
- https://www.statista.com/statistics/1047182/natural-gas-prices-for-households-european-union/
- includes gas prices of most EU countries and even a few more countries: https://ec.europa.eu/eurostat/statistics-explained/index.php/Natural_gas_price_statistics#Natural_gas_prices_for_household_consumers
Unfortunately it's only for the first half of 2020.

Seems like statista is not for free, but at first I could look at the graphs (no download though).

**Comment by SabineHaas** [comment]
while searching for electricity prices, I've found that gas prices are provided here: https://ec.europa.eu/eurostat/web/main/data/database 
haven't checked, however, whether this is what we need - just a hint for your research ;)

**Comment by MaGering** [comment]
For Germany I've already taken the gas prices from this [source](https://www.bmwi.de/Redaktion/DE/Publikationen/Studien/entwicklung-der-energiemaerkte-energiereferenzprognose-endbericht.pdf?__blob=publicationFile&v=7) on page 73.
I've documented my choices [here](https://github.com/greco-project/pvcompare/blob/feature/fossil_source_heating/docs/parameters.rst#L187-L190) on branch `feature/fossil_source_heating`:

```
        b. **Gas plant 2015 Germany**: 0.071 (Linear interpolated value from `ewi, gws, prognos [ewi_n_gas] <https://www.bmwi.de/Redaktion/DE/Publikationen/Studien/entwicklung-der-energiemaerkte-energiereferenzprognose-endbericht.pdf?__blob=publicationFile&v=7>`_ on page 73)

        c. **Gas plant 2020 Germany**: 0.076 (According to ewi_n_gas)

        d. **Gas plant 2030 Germany**: 0.085 (According to ewi_n_gas)

        e. **Gas plant 2050 Germany**: 0.096 (According to ewi_n_gas)
```

Maybe this somehow helps with the research or can serve as an orientation scanning the prices. :)
