### ISSUE TITLE
[Data] Electricity prices, feed-in tariffs, gas prices

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#209]
I've delegated #208 and #194, research about feed-in tariff and gas prices.

We could also update the electricity prices, year 2020 is available here now: https://ec.europa.eu/eurostat/databrowser/view/ten00117/default/table?lang=en

This brought me to the question: how would you like the data to be structured?

1. separate csvs for gas prices, electricity prices, feed-in tariffs 
2. one csv with columns "gas_price", etc.. (only for one year, preferably 2020 or 2019)

**Comment by Piranias** [comment]
eine csv mit Spalten fänd ich super!

**Comment by SabineHaas** [comment]
So the intended outcome would be like this (not all countries have feed-in tariff --> 0, or no information: no Value):
|   | gas_price | electricity_price | feedin_tariff
| ------------- | ------------- | ------------- |  ------------- 
| Belgium  | value  | value | 0 
| Bulgaria  |  value | value | 
| Germany  |  value | value | 0.1

@shaquille, could you have that in mind when working on #208 and #194 and directly provide the results in this format? 

Important here is that electricity_price and feedin_tariff should be of the same year.

**Comment by Piranias** [comment]
> So the intended outcome would be like this (not all countries have feed-in tariff --> 0, or no information: no Value):

I would say there is two options dealing with "no value". 
1) setting it to 0 by default or
2) setting it to e.g. 0,1 by default and giving a warning that a feedin tarif is not known for the country and therefore the simulation runs as if it would be 0,1. 

We can also decide this as soon as the inquest is done and as soon as we know if we get any reasonable results without feed-in tariff. Because I'm afraid that PV will just not be used with a feed-in tariff set to 0. But let's see.

**Comment by SabineHaas** [comment]
> > So the intended outcome would be like this (not all countries have feed-in tariff --> 0, or no information: no Value):
> 
> I would say there is two options dealing with "no value".
> 
>     1. setting it to 0 by default or
> 
>     2. setting it to e.g. 0,1 by default and giving a warning that a feedin tarif is not known for the country and therefore the simulation runs as if it would be 0,1.
> 
> 
> We can also decide this as soon as the inquest is done and as soon as we know if we get any reasonable results without feed-in tariff. Because I'm afraid that PV will just not be used with a feed-in tariff set to 0. But let's see.

Good point! I've just realized that no feed-in tariff does not mean that a prosumer doesn't receive money for the feed-in. It just means that there's no fixed tariff. I guess that usually (and this is the case for Spain and Portugal, see  https://github.com/greco-project/pvcompare/issues/194#issuecomment-766637166) a prosumer would get the market price (pool price).

**Comment by Piranias** [comment]
yes, that's also how I understood the comment for portugal and spain. So researching the pool prices should also be included into the research task, right?

**Comment by SabineHaas** [comment]
> We could also add a column "market price electricity" and in case the feed-in tariff is 0 or None we use the market price instead.

Good idea!
