### ISSUE TITLE
Update pvcompare to MVS v0.5.5

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#211]
As soon as MVS is released to v0.5.5 we need to update pvcompare.

New features (not exhaustive):
- Stratified thermal energy storage (TES) MVS 
- Constraint: Minimal degree of autonomy [MVS #726](https://github.com/rl-institut/multi-vector-simulator/pull/726)
- xlrd requirement fixed in MVS #716
- KPI: degree of NZE 
- Constraint: net zero energy [[MVS #796](https://github.com/rl-institut/multi-vector-simulator/pull/796/)]
- `fixcost.csv` can be used now [MVS #795]

Changes:
- Precision limit of results set to 10e 6 [see PR](https://github.com/rl-institut/multi-vector-simulator/pull/791)
**Definition of Degree of Autonomy has changed**
Before: `DoA = generation / demand`, now: `DoA = (demand - consumption from provider) / demand` see [MVS commit](https://github.com/rl-institut/multi-vector-simulator/pull/726/commits/48f1ea11904020930ce78c8ca25b94754999dfb9)

Adaptions to be done:
- [x] Adapt all csvs: add minimal degree of autonomy to `constraints.csv` 
- [x] Adapt pvcompare to TES, done in #148 @MaGering is there anything else to adapt or will all adaptions  be covered in #148?
- [x] Remove `xlrd` from pvcompare requirements
- [x] Check for additional parameters and remove deprecated parameters in csvs. e.g. via [test inputs MVS](https://github.com/rl-institut/multi-vector-simulator/tree/dev/tests/inputs)
- [x] Adapt requirements: fix MVS version to the new release

**Comment by MaGering** [comment]
- Minimal degree of autonomy added with merged PR https://github.com/greco-project/pvcompare/pull/231
- All adaptations of pvcompare to TES covered with merged PR https://github.com/greco-project/pvcompare/pull/148

**Comment by SabineHaas** [comment]
Could one of you, @MaGering, @Piranias update the csvs in pvcompare (second last checkbox above).
I could adapt the setup and try to fix #92 at the same time, then.

**Comment by Piranias** [comment]
> Could one of you, @MaGering, @Piranias update the csvs in pvcompare (second last checkbox above).
> I could adapt the setup and try to fix #92 at the same time, then.

I will do this now
