### ISSUE TITLE
Why the storage is not used

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#214]
I would like to discuss why the storage is almost never used in our simulations.

here's some storage parameters that we researched:

,unit,storage capacity,input power,output power
specific_costs,currency/kWh,250,0,0
specific_costs_om,currency/kWh/year,0.15,0,0
efficiency,factor,1.0,0.9,0.9
soc_initial,None or factor,None,NaN,NaN
soc_max,factor,0.8,NaN,NaN
soc_min,factor,0.1,NaN,NaN

I was wondering: if the input - AND output power efficiency is set to 0.9 the total loss is about 20 % (0,19). 
So on the one hand we earn money by grid feed-in and have no losses (and lose no money with the excess sink) and on the other hand have 20% losses AND costs with the storage. This way I don't see a reason why the storage would ever be used. Isn't it always more profitable to feed electricity into the grid and take it out when it's needed?
Am I missing something?

**Comment by SabineHaas** [comment]
I cannot remember the thing with the `dispatch_price` for the heat pump.. Actually setting a `dispatch_price` close to zero would prevent oemof to transform electricity to heat that is not needed in the heat sector - as far as I can see now, this is only necessary if `feed-in tariff = 0`. For a positive feed-in tariff this shouldn't be an issue. So, as far as I can see there's no connection to this topic, but maybe @MaGering you can remember more?

**Comment by MaGering** [comment]
> So, as far as I can see there's no connection to this topic, but maybe @MaGering you can remember more?

Unfortunately I can't remember much more besides the facts that the simulation didn't run trough as intended (maybe heat pump has not been installed?) and that we set `dispatch_price` for the heat pump to `0.00000000001` (like you said to a very small number) in `energyConversion.csv`.

Sorry for the confusion. I just had the association to this, talking about the batteries being not installed. But I as well do not see now how it could be linked. ;)

**Comment by SabineHaas** [comment]
I got it - sorry for documenting this here, as it actually is off-topic.

At first we set negative values in COP time series to zero --> heat pump cannot convert power to heat. To prevent oemof to use this to get rid of unnecessary electricity (== using heat pump as excess sink. would only happen in case of no feed-in tariff), we set a very low dispatch_price for the heat pump.

**Comment by SabineHaas** [comment]
@Piranias apart from checking input and output efficiency it could also be worthy to do a quick research on economic feasibility of battery storages in households... maybe they are just too expensive.

**Comment by c-moeller** [comment]
250 EUR/kWh is not too expensive for a storage, it's actually quite cheap, but the point that you earn money by feeding to the grid could be the reason for not installing storage. Why would the system install storage? Are there any other restrictions, like e.g. a self-sufficiency rate which has to be achieved?

**Comment by c-moeller** [comment]
Do we actually have scenarios where we don't earn money by feeding into the grid?

**Comment by Piranias** [comment]
> Do we actually have scenarios where we don't earn money by feeding into the grid?
 
no, I guess not. If a country does not have a feed-in tarif, we would use the market price of electricity instead.

**Comment by Piranias** [comment]
okay, I probably found the solution. The soc_max was set too low. It should actually be 1. It's the maximum state of charge that is possible in the storage. I then set the soc_min to 0.15 and it seems to work much better.

**Comment by SabineHaas** [comment]
Ah okay, I've actually never checked this for Li-ion batteries. Nice that it works better for you now!
Please keep in mind that when optimizing the storage capacity a result of zero capacity installed might be a "good" result, too, as batteries are expensive and not using one might just be the cost-optimal solution.

**Comment by Piranias** [comment]
> Ah okay, I've actually never checked this for Li-ion batteries. Nice that it works better for you now!
> Please keep in mind that when optimizing the storage capacity a result of zero capacity installed might be a "good" result, too, as batteries are expensive and not using one might just be the cost-optimal solution.

yes of course, maybe my answer was misleading. I just wanted to say that a max-soc of 0,8 does not make sense, because why would a battery only be charged up to 80 %? (also see mvs inputs for that). And it also explains why the battery was not very profitable, since only 70 % of the capacity was usable. This makes results more reasonable (not only for me) but of course does not mean that the battery will now always be used.
