### ISSUE TITLE
Explain default values of pvcompare in readthedocs

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#22]
Default values being used in the simulation (incl. MVS parameters in csvs) should be stated and references (and calculations if applicable) given.

**Comment by mahendrark** [comment]
Notes:

    oemof_file_name parameter within the simulation_settings.csv file seems to have been depreciated.
    store_nx_graph is set to False in MVS itself, while we set the value True.
    capex_fix within fixcost.csv has a value of 4600. I am not sure if I came up with this value. Also there is no source for it on the google sheets document.

I will update this list, as I continue working through the default parameters list for the docs.
