### ISSUE TITLE
[tests] Add tests that run examples 

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#228]
I already had a few times the problem that after changes in a PR the examples did not run without errors.  Therefore, I'd suggest to add a test that just runs the example scripts.

**Comment by SabineHaas** [comment]
@MaGering could you add a simple test for each example (just running the example)? If the examples have a long runtime I'd suggest to skip the tests if `EXECUTE_TESTS_ON` is not `"master"`

**Comment by MaGering** [comment]
Done with PR https://github.com/greco-project/pvcompare/pull/284.
