### ISSUE TITLE
Make tests run without errors

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#24]
If this is a travis issue this will be solved by @SabineHaas

**Comment by SabineHaas** [comment]
@Piranias could you please give me feedback whether you can solve this issue or whether it must be a travis issue? 
To me it looks like it's just a value that has changed in one of the last digits.

**Comment by Piranias** [comment]
Hi,
the tests run through now. I could not find out what exactly caused the error though. The test_si_timeseries() returnes a slightly different value than what I calculate locally. There was no error in my local copy. I solved the issue by rounding the value to three digits, but it is just a work around. All variables are defined within the class, I cound't explain why the function returns a different value in the remote version.
I'll still try to solve the issue but at least the tests run though now. If you have any idea what could cause this issue let me know.
