### ISSUE TITLE
Adapt csvs according to MVS PR 347

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#26]
There are API changes in the next MVS release. We need to adapt csvs and if necessary code to https://github.com/rl-institut/mvs_eland/pull/347

**Comment by smartie2076** [comment]
For all csv that are included in the github repro (tests, inputs) this was already done. For your local input files you will still need to do this.

**Comment by mahendrark** [comment]
Notes:

1. oemof_file_name parameter within the simulation_settings.csv file seems to have been depreciated.
2. store_nx_graph is set to False in MVS itself, while we set the value True.

I will update this list, as I continue working through the default parameters list for the docs.

**Comment by Piranias** [comment]
done
