### ISSUE TITLE
Adapt how to release section in contributing.md

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#268]
Before a release, one has to check that master build passes:
https://github.com/greco-project/pvcompare/actions

If build for the merge into master passes, there's no guarantee that master build passes after merge, see what happened at release v0.0.2:

- release branch check passes: https://github.com/greco-project/pvcompare/actions/runs/682609990
- master branch check fails: https://github.com/greco-project/pvcompare/actions/runs/682630899

Another option is to install pvcompare in a clean virtual environment and do the check:
- `pip install -e .[dev]` (if you are in the directory where setup.py is located)
- ` EXECUTE_TESTS_ON=master pytest`

I think I would go for the second option so that bug fixes are done before the merge into master, but additionally wait for the master build to pass before the actual release. @MaGering what do you think?

**Comment by MaGering** [comment]
For me the second option also sound like the proper one. But concerning release v0.0.2 I'm wondering if you could have seen this error. Because as far as I'm concerned you and @Piranias never had problems running the simulations from a clean environment or had you?

**Comment by SabineHaas** [comment]
> For me the second option also sound like the proper one. But concerning release v0.0.2 I'm wondering if you could have seen this error. Because as far as I'm concerned you and @Piranias never had problems running the simulations from a clean environment or had you?

Yes I had that problem now.. Apparently I wasn't aware that my virtualenv actually was not clean anymore.. I'm not a 100% sure.. But anyways I could reproduce the error now in a new env.
