### ISSUE TITLE
run_pvcompare is deprecated?

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#301]
We have two locations for basically the same file. One is run_pvcompare.py and the other one in the example folder. The only difference is that they use different input files. I find this kind of confusing. @SabineHaas , @MaGering :Do we need this fourth 'example' in run_pvcompare.py or can we just delete it?

**Comment by SabineHaas** [comment]
My idea of `run_pvcompare.py` was to provide users with a "main"-file that the can just run to start pvcompare calculations with the standard input folder. Whereas examples should show the usage of pvcompare and have a specific input. 

I would expect new users to first run different examples to explore what pvcompare is capable of and then run their own simulation with `run_pvcompare.py´ and their own input data.

**Comment by Piranias** [comment]
I mentioned it in the documentation (PR #302 )
