### ISSUE TITLE
add scenario with "lower demand" ?

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#307]
see working paper : " this work, we define NZEB as buildings whichhave a lower energy demand than conventional buildings and which meetthis demand from locally generated renewable energy while energy can beexchanged with the grid. During the period of one year a NZEB producesjust as much or more energy (NPEB) than needed to cover its demand."

-> this is not included yet. But we should keep it in mind and decide if we want to investigate this

**Comment by SabineHaas** [comment]
I would say this is a nice to have, for if we have time in the end. To my mind, usability of pvcompare e.g.  #161 and  #154 has a higher priority.

**Comment by SabineHaas** [comment]
Note: if we include this into the working paper, in introduction we should uncomment the line which is currently line 72: "which have a lower energy demand than conventional buildings and which meet this ..."
