### ISSUE TITLE
CPV time series for hybrid module

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#318]
The daily plot of SI, PSI and CPV in RTD see [here](https://pvcompare.readthedocs.io/en/latest/scenarios_and_results.html#id4) shows time series of the CPV cells, but not the hybrid module including the SI flat plate module, right?

If you find the time it would be nice to plot the time series of the hybrid module there.

**Comment by Piranias** [comment]
No, it's the hybrid module. This is only due to us naming everything "CPV" instead of "hybrid CPV". We should defenately have it consistent in the rtd though.

**Comment by SabineHaas** [comment]
hmm doesn't the hybrid module usually have peaks in the morning and evening?

**Comment by Piranias** [comment]
Yes, but they are only very small peaks compared to the CPV peaks and end out in a  (see https://pvcompare.readthedocs.io/en/latest/_images/CPV_spain_2014.png). When summing up over the whole rooftom they seem to just flatten the sides. Thats why I inculed the additional picture with the habrid, flatplate and cpv part.

**Comment by SabineHaas** [comment]
ahh I see! Thank you!!
