### ISSUE TITLE
greco_technologies needed in pvcompare?

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#319]
Do we still need [greco_technologies](https://github.com/greco-project/greco_technologies)? 

We install it in the [setup.py](https://github.com/greco-project/pvcompare/blob/cd5516527a4b13e69e9f471ab1a2cfd25d298ea8/setup.py#L45) but I am not sure whether it is actually used in pvcompare.

We can keep the repo but I would delete the requirement if it is not used in pvcompare

**Comment by Piranias** [comment]
no, we do not use it anymore. We moved the psi and cvp calculation into pvcompare.
