### ISSUE TITLE
Delete if name == main statements?

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#324]
@MaGering @Piranias 
For the release I would delete unnecessary if name == main statements in the modules.

Do you agree and are there any statements that should stay?

**Comment by MaGering** [comment]
> @MaGering @Piranias
> For the release I would delete unnecessary if name == main statements in the modules.
> 
> Do you agree and are there any statements that should stay?

I can't think of a statement I would like to keep. So they can disappear :)
