### ISSUE TITLE
[docs] links in code documentation need to be fixed

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#40]
In the[ code documentation on readthedocs](https://pvcompare.readthedocs.io/en/latest/code.html) the links (and explanatory sentence) of the module `demand` does not work.
Probably the docstrings need to be adapted.

**Comment by SabineHaas** [comment]
I think this wasn't fixed in #43. It must be something in the demand functions - the links to them don't work and there's no explanation in the docs.

**Comment by Piranias** [comment]
locally everything seems fine. I also updated the electricity_price functions. but the rtd did not update yet and is also not showing the new function

**Comment by SabineHaas** [comment]
add_electricity_price() is shown in the [dev of readthedocs](https://pvcompare.readthedocs.io/en/dev/code.html)  
Strangely not in the latest version.. need to look into that. But the demand functions look the same - no links and no explanation.

**Comment by Piranias** [comment]
hmm, but how can I know if they are shown correctly if they do seem perfect when I execute sphinx locally? Maybe this has something to do with the build?

**Comment by SabineHaas** [comment]
I'll look into it

**Comment by SabineHaas** [comment]
Also when changing what I though could cause the problems in #44, there's no change, see https://pvcompare.readthedocs.io/en/fix-demand_documentation/code.html

Also the `index.rst` does look good.. Until now I cannot see what the problem could be.
