### ISSUE TITLE
Use complete_irradiance func of pvlib

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#46]
We should use the [`complete_irradiance`](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.modelchain.ModelChain.complete_irradiance.html#pvlib.modelchain.ModelChain.complete_irradiance) function of pvlib for calculating the dni instead of ([ghi - dhi](https://github.com/greco-project/pvcompare/blob/6d37fc9a8cc6ece12fafccf20657ccea0ad8b483/pvcompare/pv_feedin.py#L499)). 

This functions calculates the missing irradiation column of dni, ghi, dhi if two of them are given.

Usage looks like this:
`mc.complete_irradiance(weather=weather, times=weather.index)`

**Comment by Piranias** [comment]
I just used this as a dummy dataset, because era.5 is taking so long and this is only for checking if the skript runs. I didn't mean to use this in the end. the whole 
"if __name__ == "__main__":" should be deleted anyways.

For my part I would leave them in for now, because it makes it easy to execute the files seperately. But I can also already clean it if more people will work on this soon

**Comment by SabineHaas** [comment]
For me it's fine if you leave them like that!

My point is rather about using complete_irradiance() somewhere in the code and delete the line where dni is approximated by ghi-dhi. Because dni is also dependent on the solar position which is taken into account into this function.

**Comment by Piranias** [comment]
Okay, then I'll leave it for now.
 I'm not sure if I used the function complete_irradiance() before. Right now the dni is calculated by pvlib.irradiance.dirint() see [here](https://github.com/greco-project/pvcompare/blob/6d37fc9a8cc6ece12fafccf20657ccea0ad8b483/pvcompare/era5.py#L43)

But if you think pvlib.complete_irradiance() is better I can check it out

**Comment by SabineHaas** [comment]
Oh, interesting - I didn't know this function. 
Complete_irradiance uses the `pvlib.irradiance.dni()` for calculating the dni, but other functions in case dni is given but not ghi or dhi.

**Comment by Piranias** [comment]
ah so I took a look and the [complete_irradiance()](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.modelchain.ModelChain.complete_irradiance.html?highlight=complete%20irradiance) function is applied within a modelchain, which is not the case in our simulation.

I don't know id the  pvlib.irradiance.dni() is a better approximation. at least is approximates dni from both ghi and dhi and not only from ghi..
