### ISSUE TITLE
Costs for pero/si and cpv technologies

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#47]
Hi,
In order to start reasonable simulations we need to estimate the costs for pero/si and cpv technologies. I know that @SabineHaas and @mahendrark, you worked on this before, right? What estimations can I can use for simulations, where are they documented?

**Comment by SabineHaas** [comment]
Hi @Piranias 
For pero/si we wanted to simulate with a range around the state-of-the-art technology's costs -- if there's a need for additional research, I would at first ask our partners working in this field.
Concerning the CPV technology's we should ask our partnersl, but in our last discussion about that we came to the conclusion that at first we need to settle on the SI costs to be able to ask whether we should assume similar costs/ very different costs for some of the parameters.
Have you decided on the SI costs? We can also discuss on Monday!

**Comment by SabineHaas** [comment]
Is this still an issue, otherwise please close @Piranias - I'm checking the open issues.
