### ISSUE TITLE
Automate black formatter

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#5]
We could use  

1. [stickler](https://stickler-ci.com/docs) as done in the [windpowerlib](https://github.com/wind-python/windpowerlib) or 

2. commit](https://pre-commit.com/) as described on the [black github repo](https://github.com/psf/black#version-control-integration).

**Comment by Piranias** [comment]
I don't mind. Which one do you think is better?

**Comment by SabineHaas** [comment]
I really got used to executing `black . --exclude docs/` before uploading code or at least being reminded by the checks that I should do it..  Now I would prefer it this way. Also because it confuses me when a bot is making commits or giving a warning about your code having an unused import, etc. (see windpowelib).
Would you be fine with that or does applying black annoy you a lot?

**Comment by Piranias** [comment]
I'm okay with that. I do forget it once in a while though ;) but I will try my best to always execute blacks before pushing

**Comment by SabineHaas** [comment]
okay :+1:
