### ISSUE TITLE
normalized or absolute pv timeseries

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#50]
option 1.) all timeseries are normalized for 1 kWp installed capacity. The development cost is also given for 1 kWp.

option 2.) all timeseries are given for a realistic module size. The costs are adapted individually for each module.

option 3.) all timeseries are scaled to a certain module area, e.g. 1m² The prices are also given for that area.

decision from 27. July (@Piranias , @SabineHaas ) : option 1

**Comment by Piranias** [comment]
after thinking about this issue again I would rather stay with option 2 and take the absolute timeseries instead of the normalized. Because scaling all time series to 1kWp would mean that we would need to adjust the price for each technology very carefully and in a non-intuitive way in order to resemble the differences between the technologies.

with option 2 we could stay with a similar price for all technologies but the modules would have a different peak power / area.

The modules are constructed as follows:

**SI** (from pvlib)
area: 1.7 m²
peak: 219 W

**CPV** (as constructed by insolight)
area: 1.2 m²
peak: 359 W

**PSI** (self constructed)
area: 0.98 m²
peak: 273 W (still without module losses)

This makes the CPV module the most efficient/area, so the price could be higher (as expected in reality).

**Comment by SabineHaas** [comment]
I agree with you and I think for future users it's easier to work with module based data.

How did you construct the PSI module? How many cells in series, how many parallel rows?

**Comment by Piranias** [comment]
> I agree with you and I think for future users it's easier to work with module based data.
> 
> How did you construct the PSI module? How many cells in series, how many parallel rows?

The PSI module is constructed of 20000 cells in series. One cell is 0.49 cm². No connection in parallel.
