### ISSUE TITLE
[PV HP] definition of heating/cooling period

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#60]
The cops/eers of heat pumps/chillers time series are calculated for a heating/cooling period, which are defined via temperatures in [`heat_pump_and_chillers.csv`](https://github.com/greco-project/pvcompare/blob/feature/heat_pump/pvcompare/data/inputs/heat_pump_and_chillers.csv)

The heating period starts at [17 degrees](https://github.com/greco-project/pvcompare/blob/822c573d8f5d75a1603454476cce4a92e82f27c2/pvcompare/data/inputs/README_for_documentation.txt#L9) 
Source:  https://www.hotmaps-project.eu/wp-content/uploads/2018/03/D2.3-Hotmaps_for-upload_revised-final_.pdf

The problem I see is that the [heat demand time series](https://github.com/greco-project/pvcompare/blob/dev/pvcompare/data/mvs_inputs/time_series/heat_load.csv) are never zero. So the cop time series does not match the heat demand time series. 

additional info:
Here is a daily average temperature profile for NUTS-2 regions for residential sites for 2010 for all european countries: https://gitlab.com/hotmaps/hotmaps_task_2.7_temperature_profile_daily_avg_household_yearlong_2010

**Comment by SabineHaas** [comment]
In our last discussion we pointed out that we should exclude water heating from the heat demand profiles.

**Comment by SabineHaas** [comment]
Is this issue solved @MaGering? If yes, you can close it.

**Comment by MaGering** [comment]
> Is this issue solved @MaGering? If yes, you can close it.

I'm afraid not. This issue also addresses the ZeroDevision Error, doesn't it? Because this problem still exists if temp_high of the heat pump is lower than the ambient temperature.

**Comment by SabineHaas** [comment]
Ah right, I see! I was trying to get an overview over all the open issues, no worries! Thank you :)

**Comment by SabineHaas** [comment]
fixed in #195
