### ISSUE TITLE
Check lifetime of inverter and charge controller

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#62]
Check references https://pvcompare.readthedocs.io/en/latest/parameters.html
and values in csvs.

**Comment by Piranias** [comment]
@SabineHaas I think this is done, no?

**Comment by SabineHaas** [comment]
I haven't checked it. But you have probably checked the values when running simulations for the project meeting, right?

**Comment by Piranias** [comment]
It's 10 years for both
