### ISSUE TITLE
[PV HP] Research on cost parameters heat pumps

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#63]
- [x] Cost parameters and lifetime of a heat pump need to be researched and added to the[ `mvs_inputs_template_sector_coupling`](https://github.com/greco-project/pvcompare/tree/feature/heat_pump/pvcompare/data/mvs_inputs_template_sector_coupling) directory.
- [x] After testing these parameters in simulations they need to be added to the [documentation](https://pvcompare.readthedocs.io/en/latest/parameters.html) including references (section energyConversion.csv).

**Comment by MaGering** [comment]
Second task completed in PR https://github.com/greco-project/pvcompare/pull/189. It will be merged into dev with PR https://github.com/greco-project/pvcompare/pull/190.

**Comment by MaGering** [comment]
Merged with PR https://github.com/greco-project/pvcompare/pull/190 into dev.
