### ISSUE TITLE
travis build fails, csv's not found in site package

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#71]
see ckecks in PR #70

**Comment by Piranias** [comment]
1) When applying the test the csv file in greco_technologies/perosi/data/CHEN_2020_EQE_curve_pero_corrected.csv is not found:
[see here](https://travis-ci.com/github/greco-project/pvcompare/jobs/372656865#L952)

**Comment by Bachibouzouk** [comment]
Maybe you need to wrap the `os.path.dirname(__file__)` with `os.path.abspath`:  `os.path.abspath(os.path.dirname(__file__))` ?

**Comment by Bachibouzouk** [comment]
You can also try to execute `os.path.join(os.path.abspath(os.path.dirname(__file__)), "program.exe")` instead of `"program.exe"`?

**Comment by Piranias** [comment]
both don't work see [build](https://travis-ci.com/github/greco-project/pvcompare/jobs/375241728)

`FileNotFoundError: [Errno 2] File b'/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/data/CHEN_2020_EQE_curve_pero_corrected.csv' does not exist`

and 


```
----------------------------- Captured stderr call -----------------------------

/bin/sh: 1: /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/program.exe: not found
```

**Comment by Piranias** [comment]
> You can also try to execute `os.path.join(os.path.abspath(os.path.dirname(__file__)), "program.exe")` instead of `"program.exe"`?

both don't work. See [build](https://travis-ci.com/github/greco-project/pvcompare/jobs/375241728)

`FileNotFoundError: [Errno 2] File b'/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/data/CHEN_2020_EQE_curve_pero_corrected.csv' does not exist`

and

```
-- Captured stderr call -----------------------------

/bin/sh: 1: /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/program.exe: not found
```

**Comment by Bachibouzouk** [comment]
https://travis-ci.community/t/no-such-file-or-directory-on-script/2592 ?

**Comment by Piranias** [comment]
> https://travis-ci.community/t/no-such-file-or-directory-on-script/2592 ?

yea, I saw these issues before. people messed up the path because they work on windows. But I'm working on linux and that's exactly why I'm using os.path.join, where the operating system should not make a difference. So I don't see that this is the point unfortunately..

**Comment by Piranias** [comment]
Problem is moved to PR  #73

**Comment by SabineHaas** [comment]
This might be solved by adding `[package_data`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#package-data) to the `setup.py` 
I think otherwise the data is just not saved in site-packages when installing the package.
More help here https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files

**Comment by Piranias** [comment]
Thanks @SabineHaas, that worked!
But there is more issues regarding the fortran code of SMARTS.
I install libgfortran in the travis.yml but I get an error now:

```
(/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/program.exe)`
```
see [build](https://travis-ci.com/github/greco-project/pvcompare/jobs/379438938) 


Here's a similar[ issue ](https://travis-ci.com/github/greco-project/pvcompare/jobs/379438938).

I don't know much about this and i have no idea how to solve this.. Do you have any idea?

**Comment by SabineHaas** [comment]
I'm sorry I couldn't find any solution to this. But it seems like this problem has occurred with older versions of GLIBC - I found issues about different versions. So, I guess, as discussed it's worth asking HH.
