### ISSUE TITLE
[Bug] Travis Ci conflicts installing gfortran compiler

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#74]
Checklist to make sure that the bug report ist complete:
- [x] OS: Ubuntu 18.04.5 LTS
- [x] Branch: psi_test
- [x] If applicable: Attach full error message
- [:x:] If applicable: Share screenshots/images of your problem
- [:x:] If applicable: Share used input data

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Checkbox is not applicable to this bug report

our code makes use of the fortran program SMARTS. Everything works fine on local machines, but Travis Ci seems to have problems with installing the fortran compiler gfortran (libgfortran4).

here's the [travis.yml](https://github.com/greco-project/pvcompare/blob/psi_test/.travis.yml)

see [build](https://travis-ci.com/github/greco-project/pvcompare/jobs/379449783#L1165)

Error message:

`(/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/greco_technologies/perosi/program.exe)``

**Comment by henhuy** [comment]
I think tavis is using wrong ubuntu version (16.04) - see build details.
This is due to travis default settings: https://docs.travis-ci.com/user/reference/linux/
Maybe this works if you set dist to "bionic" instead of "xenial"...?!

**Comment by Piranias** [comment]
> I think tavis is using wrong ubuntu version (16.04) - see build details.
> This is due to travis default settings: https://docs.travis-ci.com/user/reference/linux/
> Maybe this works if you set dist to "bionic" instead of "xenial"...?!

great, thanks this seems to work!
