### ISSUE TITLE
[documentation] update documentation of parameters

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#76]
this needs to be updated: https://pvcompare.readthedocs.io/en/latest/parameters.html

as soon as all/most values are set

**Comment by SabineHaas** [comment]
@Piranias would you see the restructuring of the parameter section in the documentation, as well here? We discussed that we do not want to display all parameters (e.g. display_nx_graph, restore_from_oemof_file, ... --> here value we use as default in the template is not very interesting for the user..)

**Comment by SabineHaas** [comment]
@Piranias I think you wanted to close this issue with #302
