### ISSUE TITLE
[Information] pvcompare is updated to latest MVS version

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#82]
@Piranias @MaGering @c-moeller 
I've just updated pvcompare to the latest MVS version and fixed the setup.py to provide a clean installation. see #81 
Once MVS is released on pypi I will update the setup.py once more   (#42). Then I think it's wise to work with a fixed MVS version and release or tag pvcompare once we want to update to a newer MVS version.

It's not merged into dev, yet. For installing pvcompare checkout the branch PR 81 and execute `pip install -e .` after navigating to the folder containing the setup.py.

Let me know in case of any installation problems or questions! 
Have fun :)

**Comment by SabineHaas** [comment]
I updated the branch `feature/update_pvcompare_packages`  (see PR #81)

Please let me know if you have installation problems. 
The pypi release of MVS is planned for Thursday - after that I will update this branch again.

**Comment by SabineHaas** [comment]
I updated the branch `feature/update_pvcompare_packages`  as discussed (see PR #81)

The pypi release of MVS is planned for Thursday - after that I will update this branch again. 

 @MaGering for using a heat pump component you can copy the files from the directory [`mvs_inputs_template_sector_coupling`](https://github.com/greco-project/pvcompare/tree/dev/pvcompare/data/mvs_inputs_template_sector_coupling) to the `mvs_inputs` folder. I found problems with the time dependent efficiency of transformers (will look into that hopefully this week) - so for now you should use a constant efficiency (change in `energyConversion.csv`).

**Comment by SabineHaas** [comment]
MVS is now installed via pypi in branch `feature/update_pvcompare_packages`.

Local installation works for me - let me know if it doesn't for you.

The travis-ci build fails, however, see [build](feature/update_pvcompare_packages).
I searched and tried a lot but couldn't find the solution.

**Comment by SabineHaas** [comment]
Update: I fixed the travis build by using a requirements.txt file again, so that at least we can merge into dev soon.
Now you have to install pvcompare via 
1. `pip install -r path/to/requirements.txt` 
2. `pip install -e path/to/directory/where/setup.py/is/located`

There is a new travis build error in all the branches now. As soon as this is solved the changes will be merged into dev.

**Comment by Piranias** [comment]
I just tried to run mvs but I get the error: 

```
  File "/home/inia/Dokumente/greco_env/lib/python3.6/site-packages/oemof/groupings.py", line 16, in <module>
    from oemof.network import Edge
ImportError: cannot import name 'Edge'
```
this is probably defined in the version of oemof or oemof.network?

**Comment by SabineHaas** [comment]
Could you upload the installed packages here, so that I can check what exactly is installed?

**Comment by Piranias** [comment]
here it is 

[pip_list.txt](https://github.com/greco-project/pvcompare/files/5370309/pip_list.txt)

**Comment by MaGering** [comment]
> here it is
> 
> [pip_list.txt](https://github.com/greco-project/pvcompare/files/5370309/pip_list.txt)

You could try to uninstall oemof 0.3.2. Maybe the package requirement of oemof.network there is in clinch to oemof.network          0.4.0rc0 that you have installed as well.

**Comment by SabineHaas** [comment]
> here it is
> 
> [pip_list.txt](https://github.com/greco-project/pvcompare/files/5370309/pip_list.txt)

You have installed MVS as developer version, whereas in the updated requirements of MVS it's installed from pypi. This might not be the problem, but could mean that you didn't install the up-to-date installation requirements. 

Another question, as I cannot read that from the error msg: did you run pvcompare or MVS when this error occurred and in which module of mvs does it occur?

**Comment by Piranias** [comment]
> > here it is
> > [pip_list.txt](https://github.com/greco-project/pvcompare/files/5370309/pip_list.txt)
> 
> You could try to uninstall oemof 0.3.2. Maybe the package requirement of oemof.network there is in clinch to oemof.network 0.4.0rc0 that you have installed as well.

no, oemof 0.3.2. was installed via the requirements of pvcompare

@SabineHaas  I was trying to run the main in pvcompare n(and pulled mvs and pvcompare to the newest version before). I didn't try only mvs yet.

**Comment by Piranias** [comment]
As well when running mvs_tool I get the error message that I have only installed the minimal configuration:

![Bildschirmfoto_2020-10-13_12-26-11](https://user-images.githubusercontent.com/44803304/95849177-669bdc00-0d4f-11eb-9dc5-134893e3cf90.png)

**Comment by SabineHaas** [comment]
Is this a MVS or pvcompare issue? 

This is to warn you that you cannot use the automatic report function of MVS because for this you need to install additional requirements (look into MVS setup.py), by heart I'd say it's pip install multi_vector_simulator[report]

**Comment by Piranias** [comment]
unfortunately I get the same error when installing everything in a new environment.
Also I had big problems installing the psycopg2 package. It only worked when I specified the package to:

psycopg2==2.7.6

maybe we should change that as well in the requirements?

Have you tried installing everything in a new environment and it worked?

**Comment by SabineHaas** [comment]
> unfortunately I get the same error when installing everything in a new environment.
> Also I had big problems installing the psycopg2 package. It only worked when I specified the package to:
> 
> psycopg2==2.7.6
> 
> maybe we should change that as well in the requirements?

psycopg2 is required in `oemof.db` see [pipdeptree.txt](https://github.com/greco-project/pvcompare/files/5372139/pipdeptree.txt)
As oemof.db requires just any version we could change the version number in our requirements. But at first let's try to find out why it works for me and not for you.

> 
> Have you tried installing everything in a new environment and it worked?

Yes, for me it did. Which python do you use? I use python 3.7.1

Could you upload the full error message and pip list of your new environment, please?

**Comment by Piranias** [comment]
I use python 3.6!

**Comment by Piranias** [comment]
ok so it runs under 3.7. I just had to define the psycopg2 version (like mentioned above) and install the cbc solver seperately.

**Comment by SabineHaas** [comment]
> ok so it runs under 3.7. I just had to define the psycopg2 version (like mentioned above) and install the cbc solver seperately.

Nice! 
But could you write an issue please referring to this issue here that pvcompare does not run with python 3.6? I would want it to run with several python versions.

So did the newest version of psycopg2 not work and you use 2.7.6 also with python 3.7?

**Comment by Piranias** [comment]
I think the error with python 3.6 only occured in mvs (do indirectly also in pvcompare, yes). Should I still write an issue in pvompare though?

I'm not shure what is the latest version. I just had to define the version. I just tried with this one..

**Comment by SabineHaas** [comment]
> I think the error with python 3.6 only occured in mvs (do indirectly also in pvcompare, yes). Should I still write an issue in pvompare though?
> 
MVS tests python 3.6 only (https://github.com/rl-institut/multi-vector-simulator/blob/4cd81ca8adc75edbe0a104785b46c3499341de29/.travis.yml#L4) - so it's really weird :D Well, no I think it's okay. We can write a test later that runs a simulation to check whether everything works (this could be an exceptional test then, that does not need to run everytime we do a PR).

> I'm not shure what is the latest version of psycopg2. I just had to define the version. I just tried with this one..

Just for me to understand.. When you installed -r requirements and setup.py the installation of psycopg2 did not work and you installed it afterwards via `pip install psycopg2==x.y.z` ?
