### ISSUE TITLE
[Bug] dev build fails for python 3.6

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#83]
see 
https://travis-ci.com/github/greco-project/pvcompare/builds/186235983

Checklist to make sure that the bug report ist complete:
- [ ] OS: *your_operating_system*, *your_distribution*
- [ ] Branch: *branch_name*, updated on *update_date_and_time*
- [x] If applicable: Attach full error message
- [ ] If applicable: Share screenshots/images of your problem
- [ ] If applicable: Share used input data

*Please mark above checkboxes as following:*
- [ ] Open
- [x] Done

:x: Checkbox is not applicable to this bug report

**Comment by SabineHaas** [comment]
This is weird as the checks had passed in the PR.

**Comment by Piranias** [comment]
> This is weird as the checks had passed in the PR.

This is strange! Do you have any idea what the bug is about or how to fix it? I don't..

```
`Adding APT Sources

185.88s$ sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"

Error: retrieving gpg key timed out.

The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .`
```

**Comment by SabineHaas** [comment]
The[ new build ](https://travis-ci.com/github/greco-project/pvcompare)passes. I read on stackoverflow that other users had similar error messages but when the build was started again it didn't occur again.
