### ISSUE TITLE
ERA5 download is time consuming

### ISSUE THREAD

**Issue by Piranias** [greco-project/pvcompare#89]
The era5 download takes about 45 min for me. Every time I change the year or location I need to wait this long. This way we will not be able to run many Simulations over many years or location. How should we deal with this?

Here's what happens. Is it possible that this due to bad internet connection? Do others have the same issue?

![Bildschirmfoto_2020-10-06_16-11-54](https://user-images.githubusercontent.com/44803304/95213115-c0038880-07ee-11eb-9b1f-6b166b8ef16d.png)

**Comment by SabineHaas** [comment]
I remember that it took also very long for me that last time I used this functionality. One option would be to download a region as big that all locations we need are included. Then we only need to download once.

**Comment by SabineHaas** [comment]
Is this still an open issue, or can we close?

**Comment by Piranias** [comment]
well we never solved this, but i guess it can be closed.
