### ISSUE TITLE
Fix travis-ci installation problems

### ISSUE THREAD

**Issue by SabineHaas** [greco-project/pvcompare#92]
Installing github repositories via 
`'cpvlib @ git+https://github.com/isi-ies-group/cpvlib.git@pvlib=0.8_fix#egg=cpvlib-0'`
works locally but fails in travis-ci, see [build](https://travis-ci.com/github/greco-project/pvcompare/jobs/398207966).

For now this was solved by moving back to a `requirements.txt` file. But this issue should be solved in the future.

Possible options:
1) release  `cpvlib` on pypi (the only package not on pypi)
2) fix in travis-ci: find expression that works for travis and locally.

**Comment by Piranias** [comment]
is this deprecated?

**Comment by SabineHaas** [comment]
I should try that with github actions.
So the idea was to only work with a setup.py, but the installation of git repositories via setup.py failed with travis, which is why I added a `requirements.txt`. I'll check whether github actions has the same problem, but it's not urgent for now, as the installation works with the `requirements.txt`, as well.

**Comment by SabineHaas** [comment]
Done in #251
